name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Update recent activity
      - name: Recent activity
        uses: Readme-Workflows/recent-activity@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Generate snake animation
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: SrustiSulipalmath
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Commit changes
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update README" || exit 0
          git push
